{% set name = "elementpath" %}
{% set version = "5.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85ed93565d6e94aefa160b12f36b12cbe4be6bf9bbde06b80f2c5c94829a25fb

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0
  run:
    - python

test:
  imports:
    - elementpath
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sissaschool/elementpath
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: XPath 1.0/2.0 parsers and selectors for ElementTree
  description: |
    The proposal of this package is to provide XPath 1.0, 2.0 and 3.0
    selectors for ElementTree XML data structures, both for the standard
    ElementTree library and for the lxml.etree library.

    For lxml.etree this package can be useful for providing XPath 2.0/3.0
    selectors, because lxml.etree already has it's own implementation of
    XPath 1.0.

  dev_url: https://github.com/sissaschool/elementpath
  doc_url: https://github.com/sissaschool/elementpath

extra:
  recipe-maintainers:
    - ccwang002
