travis:
  secure:
    BINSTAR_TOKEN: HnIXVF5rKdyxVk6RFsmLR/5ri251hdivDYxBIlPb+1cuK8/TT7wUWjErJaSU1ncfv2GZ2npxjlfeMg+4xgDgvkhatchUaHiU4lIklpPOiR+ZnD3prICqN5EKT1XhbjgFyBHbWH1CtHq1oSQkwcbVFHcI2aWjtU+ZI1I1Spl/sYSIW4/+lx9a7VwW5/QZlOYwVl6T8aQp3tU3vYB8hg2rIbX1kCI6IOLwbQLraCCkcOc0BK6khZy5XmXCjGBvZh4zQQ2HFzV5zxDG/Qh5K2FVCcNcj3mSEAmx1+LpxmdPaqlfESTXAgomMm3rHq00ZaO9kI0NJ+ZIabkn2R0fHzgiy+L2AV88z4OGT7vTIzoBJxRgc8qOSv6iRWxfpCm3VKyxFe5QEmabz0k7o9QOQQIgAWtVoFdxtKniPmugSjD6GuWXZb3YcN9+t7GUZB9Zl8UMhzBIpip3sU2zcewNHeg5yB7cU70d5DxMPxUkBRTGoRCAkG2gQKNLFhohRqoEmlQS10IiMmBzvgTznkLEnIdGhA6IOli8OI9B5HXIoUta5PEffUPhhy9yzvrxOQ7LO/aDsfO+Wzrwi1bjzK65fgb/WIpimcsEhYQDG0ltflCjdzW+SkmkK50LSg1KxYIEEGBH76jOt+yxD9ZDImDrpbgvAtWleZCuG/DaphE/L3Yb0Pw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
