travis:
  secure:
    BINSTAR_TOKEN: XrHURQ0GugHhLBkQivXRJCt3hvN2hqOZDnAuS2HUGs2sOWaMl14iQqSuLwcWuCO7Z74yvNA23VijKikM08iDZlTWiDyr6E0a9g3kikJ2X3wd3VxC6JwAmMunUMYDolye8DJLHpuuT79TMqc0Ay6a+TrOJCp8bFBqdFrRX0g4ubsv0yGOFZAKZCxRHQGzcOFipJAg7eX/Jb79yZz/i0oZezCaJWMgVkdugrS01ai7n1HvngjSYbMZk85/pVMDhcvNTQZMuSe9NFrO+mV/eh213nczBjbkcxiS/VqzHspBPT0+BQ2uQeirJY2FkDT6OwRC+yzl8Fua+r/xrdHGM1MaqxtdtIHsc7rscfXtcYuKtTP9XSTuyE4suImvApWERSkOy+oLVeyT6mpj1z5hkpnHpnwQL8Mo8ILvfxJy0/quCgW3r/NA5Eu46tFVoSBNdQ0ZNppzHWqcwfevl2pweRe/CVujBv+qDTbLZyywhz+j62WZEDTpraUfFmmwIpPQZQm8MLfY7O2GGRNGY4lGdFOQ5KFLl8JPvUr+Z308WnXAbyLVKYzTmOGrHwSL62nLj1VUV0KGRD9fUUg2LSXovmN1qOvR0T147Q54VFdppqFKnUgnovdaaqZ/HO4+h263R2zXSICFqQ4j6miZHXcTW0zZ/bgiNtM7dmd9Q0IR/VwrMDw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
